server:
  port: 8001

config:
  file:
    filesLocation: G:\Programing\java\shareFolder\v2ReadConfig\
    none: none.txt
    subscribe: subscribe.txt
  v2ray:
    main: G:\Programing\java\shareFolder\v2ray-windows-64\  #https://github.com/v2fly/v2ray-core/releases
    configFile: config.json
    testPort: 8080
    exe: v2ray.exe
    timeoutSeconds: 10
    urlTest: https://www.youtube.com
    maxPing: 1000
    maxConfig: 10
  supported-protocols: "vmess://,vless://,trojan://,shadowsocks://,http://,socks://,dokodemo-door://"
  github:
    token: "ghp_Mc0DD2II4ZyimSLHOV9pqkbgGqDHSUB4O5NIy"
    gitHubRepo: template
    branch: main
#spring:
#  datasource:
#    username: sa
#    password:
#    #url: jdbc:h2:file:e:/testdb;INIT=CREATE SCHEMA IF NOT EXISTS USER_MGMT;NON_KEYWORDS=KEY
#    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS TEMP;NON_KEYWORDS=KEY
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization : true
#    init:
#      platform: h2
#    hibernate:
#      ddl-auto: none

#  sql:
#    init:
#      data-locations:
#        - classpath:script/h2/schema.sql
